import { useState, type ReactNode } from 'react';
import {
  AIInsight, AIMarker, AISourcePopover, AppBar, Button, Card, CostBreakdown, CostCode, DataGrid, DateStepper, HoursCell,
  IPadNavBar, Keypad, KEYS, Label, Legend, Metric, MetricGroup, PageHeader, PayItemList, Popover, ProgressBar, RadioOption,
  ResourceChip, ReviewEntry, SectionHeader, SegmentedControl, SignOffQuestion, StatRow, StatusChip, Stepper, Switch,
  SyncChip, TimeCardGrid, TodaysPlan, Toolbar, GridCell, formatMoney, type Answer,
} from '@groundwork/ui';

export interface Entry { name: string; figma: string; group: 'Base' | 'Patterns' | 'Construction'; usage: string; demo: () => ReactNode; tokens: string[]; }

function SegmentDemo() { const [v, setV] = useState<'hours' | 'sign'>('hours'); return <SegmentedControl label="Panel" value={v} onChange={setV} options={[{ value: 'hours', label: 'Hours' }, { value: 'sign', label: 'Crew sign-off' }]} />; }
function SwitchDemo() { const [a, setA] = useState(false); return <Switch checked={a} onChange={setA} label="Show plug prices" />; }
function KeypadDemo() { const [v, setV] = useState('5'); const onKey = (k: (typeof KEYS)[number]) => setV((p) => (k === '⌫' ? p.slice(0, -1) : p === '0' ? k : (p + k).slice(0, 5))); return <div style={{ width: 300 }}><Keypad value={v} onKey={onKey} onApply={() => {}} /></div>; }
function SignDemo() { const [a, setA] = useState<Answer>('none'); return <div style={{ width: 320 }}><SignOffQuestion english="I left the job uninjured today." spanish="Hoy salí del trabajo sin lesiones." answer={a} onAnswer={setA} /></div>; }
function HoursDemo() { const [sel, setSel] = useState(0); return <table style={{ borderCollapse: 'collapse' }}><tbody><tr>{[5, 5].map((h, i) => <HoursCell key={i} label={`Column ${i + 1}`} value={h} selected={sel === i} onSelect={() => setSel(i)} />)}</tr></tbody></table>; }
function PopoverDemo() { const [open, setOpen] = useState(false); return <div style={{ paddingBottom: open ? 240 : 0, paddingLeft: 280 }}><Popover open={open} onClose={() => setOpen(false)} anchor={<><AIMarker onClick={() => setOpen((o) => !o)} expanded={open} /><b>$120.00</b></>}><AISourcePopover title="Read from vendor quote" source="Vendor quote PDF, page 2, line 4" confidence="High" level={0.92} onAccept={() => setOpen(false)} /></Popover></div>; }
function ReviewDemo() { const [done, setDone] = useState(false); return <div style={{ width: '100%' }}><ReviewEntry state={done ? 'accepted' : 'open'} source="Voice" entry="Installed 500 CY on 040-201100 Excavation, Scraper" evidence="“Got about five hundred yards on the scraper cut today.” 3:58 PM" onPrimary={() => setDone(true)} /></div>; }
function PayItemsDemo() { const [sel, setSel] = useState('100001'); return <div style={{ width: 280 }}><PayItemList selected={sel} onSelect={setSel} total={32041.02} items={[{ code: '100', name: 'Clear Debris', amount: 16611.99 }, { code: '100001', name: 'Clear & Grub - Heavy', amount: 15429.03, child: true }]} /></div>; }
function GridDemo() { const [col, setCol] = useState(0); return <TimeCardGrid selectedColumn={col} onSelectColumn={setCol} summary="Crew · 2 people, 1 machine" crew={[{ id: 'a', name: 'Ray Ortega', role: 'Foreman' }, { id: 'b', name: 'Cat D-3 Dozer', role: 'Linked to Ray Ortega', equipment: '02-001' }]} costCodes={[{ code: '040-201100', description: 'Excavation, Scraper', quantity: '500.0 CY' }, { code: '010-100001', description: 'Clear & Grub - Heavy', quantity: '1.0 AC' }]} hours={[[5, 5], [5, 5]]} />; }

export const ENTRIES: Entry[] = [
  // Base
  { group: 'Base', name: 'Button', tokens: ['button.'], figma: 'Button (Style, Size, State, Label, Show plus)', usage: 'One primary per view. Sentence case. Every add action is "+ Add [thing]".', demo: () => <><Button>Apply</Button><Button variant="secondary">Review</Button><Button variant="tertiary" showPlus>Add resource</Button><Button size="sm" variant="secondary">Small</Button><Button disabled>Disabled</Button></> },
  { group: 'Base', name: 'StatusChip', tokens: ['status-chip.', 'chip.'], figma: 'Status chip', usage: 'One status scale for bids, quotes, time cards and agents. Color plus text, never color alone.', demo: () => <>{(['draft', 'in-progress', 'quoted', 'approved', 'attention'] as const).map((s) => <StatusChip key={s} status={s} />)}</> },
  { group: 'Base', name: 'ResourceChip', tokens: ['resource-chip.', 'chip.'], figma: 'Resource chip', usage: 'Resource-type colors shared by estimates and time cards.', demo: () => <>{(['labor', 'equipment', 'material', 'subcontractor', 'other'] as const).map((t) => <ResourceChip key={t} type={t} />)}</> },
  { group: 'Base', name: 'SyncChip', tokens: ['sync-chip.', 'chip.radius'], figma: 'Sync chip', usage: 'On every field record so foremen know if data reached the office.', demo: () => <><SyncChip state="device" /><SyncChip state="sent" /></> },
  { group: 'Base', name: 'CostCode', tokens: ['cost-code.'], figma: 'Cost code tag', usage: 'One cost code format across products.', demo: () => <><CostCode code="040-201100" /><CostCode code="CLH" /></> },
  { group: 'Base', name: 'AIMarker', tokens: ['ai-marker.'], figma: 'AI marker', usage: 'The only marker for AI-produced values. Clickable when it opens the source.', demo: () => <><AIMarker /> <span>Read from vendor quote</span></> },
  { group: 'Base', name: 'SegmentedControl', tokens: ['segment.'], figma: 'Segment', usage: 'Switch between 2–4 views. Height follows size/target.', demo: () => <SegmentDemo /> },
  { group: 'Base', name: 'Switch', tokens: ['switch.'], figma: 'Switch', usage: 'Off state keeps an outline and an ON/OFF label.', demo: () => <SwitchDemo /> },
  { group: 'Base', name: 'Label', tokens: ['type.label', 'type.mono', 'page.fg-muted'], figma: 'Label', usage: 'Eyebrow label above panels, lists and metrics.', demo: () => <Label>Pay items</Label> },
  { group: 'Base', name: 'Metric / MetricGroup', tokens: ['type.label', 'layout.xl'], figma: 'Metric (Size)', usage: 'Label with a large tabular value.', demo: () => <MetricGroup><Metric label="Cost" value={formatMoney(15429.03)} /><Metric label="Markup" value={formatMoney(0)} /></MetricGroup> },
  { group: 'Base', name: 'RadioOption', tokens: ['grid.selected-border', 'page.fg-muted'], figma: 'Radio option', usage: 'Shows the selected option in a row, e.g. the chosen vendor.', demo: () => <><RadioOption label="Adam’s Pipe Supply" /><RadioOption label="ACE Contractors" selected={false} /></> },
  { group: 'Base', name: 'ProgressBar', tokens: ['progress.'], figma: '(inside Cost breakdown / Today’s plan)', usage: 'Single or stacked progress; segment colors must be token variables.', demo: () => <div style={{ width: 300 }}><ProgressBar label="40% installed" segments={[{ value: 0.4 }]} /></div> },
  { group: 'Base', name: 'Card', tokens: ['card.'], figma: '(container)', usage: 'Raised container used by both products.', demo: () => <Card style={{ width: 260 }}><Label>Activity notes</Label><span>Clear and grub the full ROW.</span></Card> },
  // Patterns
  { group: 'Patterns', name: 'AppBar', tokens: ['app-bar.'], figma: 'App bar (Active, Product, Search placeholder, Initials)', usage: 'Header for every HCSS web product. Active tab gets the brand indicator.', demo: () => <div style={{ width: '100%' }}><AppBar product="HeavyBid" tabs={['Projects', 'Estimates', 'Quotes']} active="Estimates" searchPlaceholder="Search estimate" /></div> },
  { group: 'Patterns', name: 'PageHeader', tokens: ['page.border', 'page.fg-muted', 'type.label'], figma: 'Page header', usage: 'Breadcrumb, title, status, optional metric, one secondary and one primary action.', demo: () => <div style={{ width: '100%' }}><PageHeader breadcrumb="Estimates / STB001" title="Downtown Eastside Drainage" status="in-progress" metric={{ label: 'Bid total', value: '$173,762.50' }} secondaryAction={<Button variant="secondary">Review</Button>} primaryAction={<Button>Generate proposal</Button>} /></div> },
  { group: 'Patterns', name: 'IPadNavBar', tokens: ['nav-bar.'], figma: 'iPad nav bar', usage: 'Back, centered title, sync state, optional action.', demo: () => <div style={{ width: '100%' }}><IPadNavBar backLabel="Jobs" title="Time card · 07-1960" action={<Button>Send</Button>} /></div> },
  { group: 'Patterns', name: 'SectionHeader', tokens: ['page.fg-muted', 'type.small', 'layout.md'], figma: 'Section header', usage: 'Card header: optional cost code, title, meta, trailing value.', demo: () => <div style={{ width: '100%' }}><SectionHeader code="CLH" title="Heavy Clearing crew" meta="3.00 shifts" trailing={<b>$5.14 / CY</b>} /></div> },
  { group: 'Patterns', name: 'Toolbar + Legend', tokens: ['grid.best-bg', 'grid.best-tag', 'page.border'], figma: 'Toolbar, Legend', usage: 'Row of controls; legend explains grid marks.', demo: () => <div style={{ width: '100%' }}><Toolbar end={<Legend items={[{ mark: 'ai', label: 'Read from vendor quote' }, { mark: 'best', label: 'Lowest price' }, { mark: 'empty', label: 'No bid' }]} />}><Button variant="secondary" showPlus>Add vendor</Button></Toolbar></div> },
  { group: 'Patterns', name: 'Stepper', tokens: ['stepper.'], figma: 'Stepper step', usage: 'Shows where a record is in its lifecycle.', demo: () => <Stepper label="Quote folder" steps={[{ label: 'Created', state: 'done' }, { label: 'Quoted', state: 'current' }, { label: 'Done', state: 'upcoming' }]} /> },
  { group: 'Patterns', name: 'DataGrid / GridCell', tokens: ['grid.'], figma: 'Grid cell (Kind, Align, Highlight, Show AI, Tag)', usage: 'Tabular numbers, right-aligned values, "—" for empty, lowest-price highlight.', demo: () => <div style={{ width: '100%' }}><DataGrid<{ v: string; p: number | null }> rowKey={(r) => r.v} rows={[{ v: 'ACE Contractors', p: 145 }, { v: 'Adam’s Pipe Supply', p: 120 }, { v: 'Dave’s Pipe Constr.', p: null }]} columns={[{ key: 'v', header: 'Vendor', render: (r) => r.v }, { key: 'p', header: 'Unit price', align: 'right', render: (r) => formatMoney(r.p), cell: (r) => (r.p === 120 ? { highlight: 'best', tag: 'Lowest', showAI: true } : {}) }]} /></div> },
  { group: 'Patterns', name: 'HoursCell', tokens: ['hours-cell.', 'grid.selected-bg', 'grid.selected-border'], figma: 'Hours cell', usage: 'Big tabular hour entry; selected column is edited by the keypad.', demo: () => <HoursDemo /> },
  { group: 'Patterns', name: 'Keypad', tokens: ['keypad.'], figma: 'Keypad key / Keypad', usage: 'One numeric keypad everywhere in field apps.', demo: () => <KeypadDemo /> },
  { group: 'Patterns', name: 'SignOffQuestion', tokens: ['button.primary-bg', 'button.secondary-border', 'button.height-md'], figma: 'Sign-off question', usage: 'Crew attestation with Spanish under English; selected answer shows a check.', demo: () => <SignDemo /> },
  { group: 'Patterns', name: 'StatRow', tokens: ['page.border', 'type.body'], figma: 'Stat row', usage: 'Label / value pair for summaries.', demo: () => <div style={{ width: 320, display: 'grid', gap: 8 }}><StatRow label="Planned" value="3,200 CY / shift" /><StatRow label="Reported today" value="500 CY" /></div> },
  { group: 'Patterns', name: 'Popover + AISourcePopover', tokens: ['popover.', 'ai-marker.'], figma: 'Popover, AI source popover', usage: 'Anchored floating content; the AI version always shows source and confidence. Click the AI marker.', demo: () => <PopoverDemo /> },
  { group: 'Patterns', name: 'ReviewEntry', tokens: ['review.'], figma: 'Review entry', usage: 'One item of an AI agent draft, accepted individually. Click Accept.', demo: () => <ReviewDemo /> },
  { group: 'Patterns', name: 'GridCell (standalone)', tokens: ['grid.'], figma: 'Grid cell', usage: 'Use inside custom tables when DataGrid is too rigid.', demo: () => <table style={{ borderCollapse: 'collapse' }}><tbody><tr><GridCell align="right">$145.00</GridCell><GridCell align="right" highlight="best" tag="Lowest" showAI>$120.00</GridCell><GridCell align="right" highlight="selected">5</GridCell></tr></tbody></table> },
  // Construction
  { group: 'Construction', name: 'PayItemList', tokens: ['card.bg', 'grid.selected-bg', 'grid.selected-border', 'type.mono'], figma: 'Pay item list / Pay item row', usage: 'HeavyBid pay-item navigator; child activities are indented.', demo: () => <PayItemsDemo /> },
  { group: 'Construction', name: 'CostBreakdown', tokens: ['resource-chip.', 'progress.track'], figma: 'Cost breakdown', usage: 'Cost by resource type, colored with the same resource tokens as the chips.', demo: () => <div style={{ width: '100%' }}><CostBreakdown costs={{ labor: 5610.87, equipment: 9818.16 }} /></div> },
  { group: 'Construction', name: 'AIInsight', tokens: ['ai-marker.', 'card.radius'], figma: 'AI insight', usage: 'AI summary card that always names its source.', demo: () => <div style={{ width: 300 }}><AIInsight title="Changes since yesterday" source="estimate audit log, 2 entries" items={['Pay item 300 unit price set to $115.00 (suggested $109.16).']} actions={<Button size="sm" variant="secondary">Open audit log</Button>} /></div> },
  { group: 'Construction', name: 'DateStepper', tokens: ['button.height-md', 'type.label'], figma: 'Date stepper', usage: 'Previous / next day for field records.', demo: () => <DateStepper relative="Yesterday" date="Thu, Aug 2" /> },
  { group: 'Construction', name: 'TimeCardGrid + CrewMemberCell', tokens: ['grid.header-bg', 'grid.row-border', 'hours-cell.', 'type.number'], figma: 'Time card grid, Time card row, Crew member cell', usage: 'Crew × cost-code hours; equipment nested under its operator. Click a column.', demo: () => <div style={{ width: '100%' }}><GridDemo /></div> },
  { group: 'Construction', name: 'TodaysPlan', tokens: ['progress.', 'cost-code.', 'type.label'], figma: 'Today’s plan', usage: 'Structured plan from the estimate, shown in the field app.', demo: () => <div style={{ width: 360 }}><TodaysPlan code="040-201100" activity="Excavation, Scraper" stats={[{ label: 'Planned', value: '3,200 CY / shift' }]} installed={{ done: 29382, total: 738897, unit: 'CY' }} crew={[{ type: 'equipment', label: 'Cat D6 Dozer' }, { type: 'labor', label: '5 × Operator' }]} /></div> },
];
