// Groundwork token build: 4 layers -> dist/tokens.css, dist/tokens.d.ts, dist/resolved.json
// Layer rules (enforced): semantic base/brand may only reference primitive; component may only reference semantic.
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, 'src');
const out = join(here, 'dist');
const read = (f) => JSON.parse(readFileSync(join(src, f), 'utf8'));
const MODES = ['office-light', 'office-dark', 'field'];

function flatten(obj, prefix = [], acc = {}) {
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith('$')) continue;
    if (v && typeof v === 'object' && '$value' in v) acc[[...prefix, k].join('.')] = v.$value;
    else if (v && typeof v === 'object') flatten(v, [...prefix, k], acc);
  }
  return acc;
}
const cssName = (path) => '--' + path.replace(/\./g, '-');
const refOf = (v) => (typeof v === 'string' && /^\{.+\}$/.test(v) ? v.slice(1, -1) : null);

const primitive = flatten(read('primitive.json'));
const base = Object.fromEntries(MODES.map((m) => [m, flatten(read(`semantic-base.${m}.json`))]));
const brandFiles = readdirSync(src).filter((f) => f.startsWith('semantic-brand.'));
const brands = Object.fromEntries(brandFiles.map((f) => {
  const name = f.replace('semantic-brand.', '').replace('.json', '');
  const doc = read(f);
  return [name, Object.fromEntries(MODES.map((m) => [m, flatten(doc[m])]))];
}));
const component = flatten(read('component.json'));

// ---- validation ----
const errors = [];
const semanticNames = new Set([
  ...MODES.flatMap((m) => Object.keys(base[m])),
  ...Object.values(brands).flatMap((b) => MODES.flatMap((m) => Object.keys(b[m]))),
]);
for (const m of MODES) {
  const baseKeys = Object.keys(base['office-light']).sort().join();
  if (Object.keys(base[m]).sort().join() !== baseKeys) errors.push(`semantic-base.${m}: token names differ from office-light`);
  for (const [k, v] of Object.entries(base[m])) {
    const r = refOf(v);
    if (!r) errors.push(`semantic-base.${m} ${k}: must reference a primitive, got literal ${v}`);
    else if (!(r in primitive)) errors.push(`semantic-base.${m} ${k}: {${r}} is not a primitive`);
  }
}
for (const [b, perMode] of Object.entries(brands)) for (const m of MODES) for (const [k, v] of Object.entries(perMode[m])) {
  const r = refOf(v);
  if (!r) errors.push(`semantic-brand.${b}.${m} ${k}: must reference a primitive`);
  else if (!(r in primitive)) errors.push(`semantic-brand.${b}.${m} ${k}: {${r}} is not a primitive`);
  if (k in base[m]) errors.push(`semantic-brand.${b} ${k}: collides with a semantic base token`);
}
for (const [k, v] of Object.entries(component)) {
  if (semanticNames.has(k) || k in primitive) errors.push(`component ${k}: name collides with a lower-layer token`);
  const r = refOf(v);
  if (r && !semanticNames.has(r)) errors.push(`component ${k}: {${r}} must reference a semantic token (base or brand)`);
  if (!r && /^#|px$/.test(String(v))) errors.push(`component ${k}: raw color/dimension "${v}" not allowed, alias a semantic token`);
}
if (errors.length) { console.error('Token build failed:\n  ' + errors.join('\n  ')); process.exit(1); }

// ---- emit CSS ----
const decl = (name, v) => `  ${cssName(name)}: ${refOf(v) ? `var(${cssName(refOf(v))})` : v};`;
const lines = ['/* Generated by packages/tokens/build.mjs. Do not edit. */', '', '/* Layer 1: primitive */', ':root {'];
for (const [k, v] of Object.entries(primitive)) lines.push(decl(k, v));
lines.push('}', '');
// Component tokens are declared on every mode wrapper (not :root) so var() chains resolve
// against that wrapper's semantic values; nested wrappers re-resolve automatically.
lines.push('/* Layer 4: component (declared on each [data-mode] wrapper) */', '[data-mode] {');
for (const [k, v] of Object.entries(component)) lines.push(decl(k, v));
lines.push('}', '');
lines.push('/* Layer 2: semantic base, per mode */');
for (const m of MODES) {
  lines.push(`[data-mode="${m}"] {`, `  color-scheme: ${m === 'office-light' ? 'light' : 'dark'};`);
  for (const [k, v] of Object.entries(base[m])) lines.push(decl(k, v));
  lines.push('}');
}
lines.push('', '/* Layer 3: semantic brand, per brand x mode */');
for (const [b, perMode] of Object.entries(brands)) for (const m of MODES) {
  lines.push(`[data-brand="${b}"][data-mode="${m}"], [data-brand="${b}"] [data-mode="${m}"], [data-mode="${m}"] [data-brand="${b}"] {`);
  for (const [k, v] of Object.entries(perMode[m])) lines.push(decl(k, v));
  lines.push('}');
}
mkdirSync(out, { recursive: true });
writeFileSync(join(out, 'tokens.css'), lines.join('\n') + '\n');

// ---- resolved.json for docs ----
const resolvePrim = (v) => { const r = refOf(v); return r ? primitive[r] : v; };
const resolved = { modes: MODES, brands: Object.keys(brands), layers: {
  primitive: Object.entries(primitive).map(([name, value]) => ({ name, value })),
  semanticBase: Object.keys(base['office-light']).map((name) => ({ name, values: Object.fromEntries(MODES.map((m) => [m, { ref: refOf(base[m][name]), value: resolvePrim(base[m][name]) }])) })),
  semanticBrand: Object.fromEntries(Object.entries(brands).map(([b, pm]) => [b, Object.keys(pm['office-light']).map((name) => ({ name, values: Object.fromEntries(MODES.map((m) => [m, { ref: refOf(pm[m][name]), value: resolvePrim(pm[m][name]) }])) }))])),
  component: Object.entries(component).map(([name, v]) => ({ name, ref: refOf(v), value: refOf(v) ? null : v })),
} };
writeFileSync(join(out, 'resolved.json'), JSON.stringify(resolved, null, 2));

// ---- types ----
const all = [...Object.keys(primitive), ...semanticNames, ...Object.keys(component)].map((n) => `'${cssName(n)}'`);
writeFileSync(join(out, 'tokens.d.ts'), `export type TokenVar =\n  | ${all.join('\n  | ')};\n`);
console.log(`tokens: ${Object.keys(primitive).length} primitive, ${Object.keys(base['office-light']).length} semantic base x ${MODES.length} modes, ${Object.keys(brands['hcss']['office-light']).length} brand x ${Object.keys(brands).length} brands, ${Object.keys(component).length} component`);
